services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    logging:
      driver: fluentd          # ← usa el driver de fluentd en vez del default
      options:
        fluentd-address: localhost:24224   # ← a dónde mandar los logs
        tag: app   
        fluentd-async: "true"
    restart: unless-stopped
    env_file:
      - .env
    stdin_open: true
    tty: true
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./quotes:/pdfs
    networks: 
      - prisma-network 

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prisma-studio
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5555:5555"
    networks:
      - prisma-network
    command: >
      sh -c "pnpm prisma studio --port 5555 --browser none"


  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    logging:
      driver: fluentd         
      options:
        fluentd-address: localhost:24224
        tag: postgres   
        fluentd-async: "true"
    networks: 
      - prisma-network
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*' 


  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - prisma-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./quotes:/pdfs
    depends_on:
      - app
    logging:
      driver: fluentd          # ← usa el driver de fluentd en vez del default
      options:
        fluentd-address: localhost:24224   # ← a dónde mandar los logs
        tag: nginx
        fluentd-async: "true"
    networks:
      - prisma-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command:
      - "http"
      - "nginx:80"
      - "--pooling-enabled"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - nginx
    networks:
    - prisma-network

  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    restart: unless-stopped
    user: "10001:10001"
    ports:
      - "3100:3100"
    volumes:
      - ./logging/loki-config.yml:/etc/loki/loki-config.yml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - prisma-network

 
      
  fluent-bit:
    image: fluent/fluent-bit:3.0
    container_name: fluent-bit
    restart: unless-stopped
    ports:
      - "24224:24224"      # Recibe logs via fluentd driver
      - "24224:24224/udp"
    volumes:
      - ./logging/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./logging/parsers.conf:/fluent-bit/etc/parsers.conf:ro
    depends_on:
      - loki
    networks:
      - prisma-network

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana_data:/var/lib/grafana
      - ./logging/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - loki
    networks:
      - prisma-network

networks: 
  prisma-network:
    name: prisma-network
volumes:
  postgres_data:
  loki_data:
  grafana_data: