events { }

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;

    location /pdfs/ {
      alias /pdfs/;
      autoindex off;

      location ~* \.pdf$ {
        add_header Content-Type application/pdf;
        add_header Content-Disposition inline;
        expires 7d;
        add_header Cache-Control "public, immutable";
      }

      location ~* [^/]$ {
        deny all;
      }
    }

    location / {
      proxy_pass http://app:3000;
    }
  }
}