[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224
    Buffer_Chunk_Size 1M
    Buffer_Max_Size   6M

[FILTER]
    Name   record_modifier
    Match  *
    Record hostname ${HOSTNAME}

[OUTPUT]
    Name            loki
    Match           *
    Host            loki
    Port            3100
    Labels          job=docker, container=$container_name, tag=$tag
    Label_Keys      $container_name,$tag
    Auto_Kubernetes_Labels off
    Line_Format     json